import { Inter } from "@next/font/google";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        {session ? (
          <>
            <span>Signed in as {session.user?.email}</span>
            <button
              onClick={() => {
                signOut().catch(console.error);
              }}
            >
              Sign Out
            </button>
          </>
        ) : (
          <>
            <span>Not signed in!</span>
            <button
              onClick={() => {
                signIn().catch(console.error);
              }}
            >
              Sign In
            </button>
          </>
        )}
      </main>
    </>
  );
}
